server:
    port: 8485
spring:
   data.mongodb:
      host: localhost
      port: 27017
      database: permalinks
      username: permalinks
      password: per001


backup:
    aws:
        accessKey: AKIAR52KNJY7MR2JM6FR
        secretKey: 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
        bucketName: aeris-permalink-test-bucket
---

spring.profiles: distant-prod
spring:
   data.mongodb:
      host: 193.52.225.51
      
---

spring.profiles: prod
backup:
    aws:
        bucketName: aeris-permalink-bucket    
  
---

spring.profiles: test
        