server:
    port: 8485
spring:
   data.mongodb:
      host: localhost
      port: 27017
      database: permalinks
      username: permalinks
      password: ENC(2vpqTI2CaFyi0zUVaODZ3w==)
info:
    code:
        front: https://sourcesup.renater.fr/projects/aerispermalink
        back: https://sourcesup.renater.fr/projects/permalinkvjs
    hosting:
        folder: ${application.folder}
    folders: none
    database:
        type: mongo
        location: SEDUR
    archive:
        type: AWS S3


orcid:
   clientId: ENC(MiZjpnEBwTdGQ5ReVY9RitTePzkT7wDZluojqDumr7U=)
   clientSecret: ENC(/W7HGnGvT8702mz23bGBlg/BosDa9Yr1Iin0iNMIIoJHbXb28Fze8kxTe46U+xRA)
   tokenUrl: https://orcid.org/oauth/token
   publicApiUrl: https://pub.orcid.org/v2.0

backup:
    aws:
        accessKey: ENC(3uogizHH5YbhHdVZf9dBDblDU2Wa0uoqIHuRaZsZT3Q)
        secretKey: ENC(eI2rgLoIqKYk7lS/gdiErXCBedFCtPD1XgWAruUU1lHe3Brc64Pzgq9YWrGS8L7Y1uEm+Sn8GGQ=)
        bucketName: aeris-permalink-test-bucket
---

spring.profiles: distant-prod
spring:
   data.mongodb:
      port: 27018
      
---

spring.profiles: prod

springdoc:
  swagger-ui:
    configUrl: /${spring.application.name}/v3/api-docs/swagger-config
    oauth2RedirectUrl: https://api.sedoo.fr/${spring.application.name}/swagger-ui/oauth2-redirect.html
    url: /${spring.application.name}/v3/api-docs/
  server.url:  https://api.sedoo.fr/${spring.application.name}

spring:
   data.mongodb:
      host: sedur

server.port: 0

backup:
    aws:
        bucketName: aeris-permalink-bucket
eureka:
  client:
    serviceUrl:
      defaultZone:  http://localhost:8761/eureka
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 5

---

spring:
   profiles: monitoring
   boot:
       admin:
           client:
               url: https://monitoring.sedoo.fr
               auto-deregistration: true

info:
  api: https://api.sedoo.fr/${spring.application.name}/swagger-ui/index.html
  code:
    front: none
    back: Sourcesup
  folders: none
  database:
    type: mongo
    location: SEDUR
  archive: none

endpoints:
    enabled: true
    health:
        enabled: true
    info:
        enabled: true  
        
        
management.info.env.enabled: true
  
management:
    endpoints:
      web:
        exposure:
          include: "*"
    endpoint:
        info:
            enabled: true
        health:
            show-details: "ALWAYS"
            northstar:
                cacheup: 240
                cachedown: 120 


---

spring.profiles: test
        